### ISSUE TITLE
Boolean bug in knpkx()

### ISSUE THREAD

**Issue by TomHyer** [basil00/Gull#10]
Line 1768 (as of Feb 2017) contains the parenthesized quantity
DATA->SArea[lsb(King(me))] && DATA->SArea[lsb(King(opp))] & Line(me, 7)

The use of '&&' here is wrong (SArea[j] is always nonzero).  It should be '&' as on line 1773.

**Comment by basil00** [comment]
Yes, another good catch.

Btw, if you like you should submit a (one line) patch as a pull request.  That way you get credit for the fix and also be listed as a contributor.

**Comment by TomHyer** [comment]
I'll try.  I suck at MinGW, haven't built your code yet.

**Comment by basil00** [comment]
In this case the change is so trivial it should not require testing.
