### ISSUE TITLE
Gull playing Chess Variants, Musketeer Chess

### ISSUE THREAD

**Issue by musketeerchess** [basil00/Gull#15]
Hi
It'll be nice to see your engine compete in the future Musketeer Chess tournaments that i'm organising.

Some interesting issues and repositories can be found here:

http://talkchess.com/forum3/viewtopic.php?f=7&t=72572&start=10#p822789

ianfab/Musketeer-Stockfish#3

Best regards
Dr HADDAD
www.musketeerchess.net

**Comment by basil00** [comment]
This version of the engine is no longer maintained, although other variants may be out there.
