### ISSUE TITLE
update of gull to play funnier games, chess variants, musketeer chess, bughouse, ordo chess

### ISSUE THREAD

**Issue by raphaeleliekakou** [basil00/Gull#16]
hi, i'm new here. can you make efforts and update your engine to be able to play musketeer chess and other variants (bughouse, orda chess).
mr ianfab is doing a great job with his fairy-stockfish and musketeer chess and many other games will be available, and playable on winboard.

saw that you have different personalities which is really unique (reminds me when i was Younger there was a program chess master with many entertaining features like those personalities. i loved to play against world champion personalities and finished by creating and improving my own ones).

i see some links that can be useful: https://github.com/ianfab/Fairy-Stockfish and this one also https://github.com/fsmosca/musketeer-chess and inventor website www.musketeerchess.net

thanks for seriously considering this add.

**Comment by basil00** [comment]
This project is inactive so it is unlikely there will be any more updates moving forward.
