### ISSUE TITLE
Gull not quitting in all cases when "quit" command is sent (Mac)

### ISSUE THREAD

**Issue by MichaelB7** [basil00/Gull#3]
adding the two lines below will ensure Gull quits...

line: 6944 #endif
        exit(0);
++      int pid;  
++      killpg(getpgid(pid), SIGTERM);

**Comment by basil00** [comment]
It seems the Linux version relies on this:

```
 prctl(PR_SET_PDEATHSIG, SIGHUP);
```

to kill the children when the parent exits.  This is a nice solution since it'll work no matter how the parent exits, but it is Linux specific.  I'll think about this some more.

**Comment by basil00** [comment]
The latest version (LazyGull) includes a posix-compliant method for terminating child processes, so this issue should be fixed.  Note however that the latest version has yet to be ported to the Mac.
