### ISSUE TITLE
PGO Makefile

### ISSUE THREAD

**Issue by MichaelB7** [basil00/Gull#4]
Added 250K nps by using PGO

https://github.com/MichaelB7/Gull/pull/1/files

Pseudo Bench - Go Depth 16

info depth 16 seldepth 37 score cp 22 nodes 14834252 nps 2032089 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 g8f6 f1d3 f8e7 b1c3 b8c6 e1g1 e8g8 f1e1 c8g4
info nodes 15530173 score cp 22
bestmove e2e4 ponder e7e6

2.032M nps
previously it was about 1.7M+ nps.

**Comment by basil00** [comment]
Thanks, I should integrate the MacOSX PGO build makefile.  Unfortunately the build system is a bit of a mess because of the combinatorial explosion of configurations (OS+(no)syzygy+(no)BMI2+(no)PGO, etc.).

**Comment by MichaelB7** [comment]
No worries - Gull is awesome!
https://www.dropbox.com/s/cx9vntj8n8mywm2/elota.txt?dl=0

If you use gcc , check out the flags I'm using. Big Increase with nos with pgo.

**Comment by basil00** [comment]
The build system was replaced; and includes a PGO build option.  So I think this can be closed.
