### ISSUE TITLE
Possible segfault in eval_king

### ISSUE THREAD

**Issue by TomHyer** [basil00/Gull#7]
We have 
	int cnt = Opening(PVarC(EI, king_att, me));
followed by
	int adjusted = ((score * KingAttackScale[cnt]) >> 3) + EI.PawnEntry->shelter[opp];

Since KingAttackScale has size 16, this access can be out-of-range if cnt>15, with unpredictable results.  An example board for which this will occur is FEN "5Q1Q/8/6k1/8/8/8/8/5RKR".

This can be corrected by changing the firstline to 
	int cnt = Min(15, Opening(PVarC(EI, king_att, me)));
or the second to
	int adjusted = ((score * KingAttackScale[Min(15, cnt)]) >> 3) + EI.PawnEntry->shelter[opp];

**Comment by basil00** [comment]
Thanks for the report.  I don't really understand that part of the code though...
