### ISSUE TITLE
kqkrpx() inaccurate

### ISSUE THREAD

**Issue by TomHyer** [basil00/Gull#9]
This function looks for a fortress where a weak-side pawn defends the rook, and the rook fences the strong-side king away from the pawn.  

For some reason it only recognizes fortresses with the pawn on its own second rank -- "OwnLine(me, 6)" in the code (me = strong-side).  

Current code:
    uint64_t pawns = DATA->SArea[lsb(King(opp))] & DATA->PAtt[me][rsq] & Pawn(opp) & Interior & Line(me, 6);
    if (pawns && CRank(me, lsb(King(me))) <= 4) return 0;

Minimal improvement:
    uint64_t pawns = DATA->SArea[lsb(King(opp))] & DATA->PAtt[me][rsq] & Pawn(opp) & Interior;
    if (pawns && CRank(me, lsb(King(me))) < CRank(me, rsq)) return 0;

Probably even better:
    uint64_t pawns = DATA->SArea[lsb(King(opp))] & DATA->PAtt[me][rsq] & Pawn(opp) & Interior;
    if (Multiple(pawns)) return 0;
    if (pawns)
    {
        int ksq = lsb(King(me)), psq = lsb(pawns);
        if (CRank(me, ksq) < CRank(me, rsq) || ((File(ksq) < File(rsq)) == (File(rsq) < File(psq)))) return 0;
    }

This tries to capture all cases where the strong-side king cannot reach the fortress pawn.  I am not 100% certain that all such fortresses are unbreakable, though.

**Comment by basil00** [comment]
I haven't looked at the code yet, but if you think it is worthwhile then please prepare a pull request.  If there is any evidence of elo gain then it will definitely be included.  Now if only there was a birdtest framework...

**Comment by TomHyer** [comment]
I'll try.   Last time I tried to build LazyGull locally I couldn't, but that was a couple months ago. 

I don't have the skills to run a bird test.  There are some vague instructions on the fish test repo, but it starts with having a server and a local instance of Mongo.  

Did you see https://github.com/TomHyer/Roc ?

Tom

**Comment by TomHyer** [comment]
Oops, Gull is right, I am wrong.  The fortress only holds if pawn is on its second rank.

**Comment by basil00** [comment]
Ah well, next time then...
